### caso 1, todo ok flujo completo
POST http://localhost:8099/start
Content-Type: application/json

{ 
 "num_socio": "123456", 
 "especialidad": "Cardiología", 
 "motivo": "Chequeo general" 
}

### caso 2, cliente vacio (error de negocio en ValidarDatosPacienteHandler)
POST http://localhost:8099/start
Content-Type: application/json

{ 
 "num_socio": "", 
 "especialidad": "Cardiología", 
 "motivo": "Chequeo general" 
}

### caso 3, motivo vacio (error de negocio en ValidarDatosPacienteHandler)
POST http://localhost:8099/start
Content-Type: application/json

{ 
 "num_socio": "123456", 
 "especialidad": "Cardiología", 
 "motivo": "" 
}
### caso 4, socio con deuda (error de negocio en VerificarCoberturaPacienteHandler)
POST http://localhost:8099/start
Content-Type: application/json

{ 
 "num_socio": "999", 
 "especialidad": "Cardiología", 
 "motivo": "Chequeo general" 
}

### caso 5, especialidad no cubierta por el plan (error de negocio en VerificarCoberturaPacienteHandler)
POST http://localhost:8099/start
Content-Type: application/json

{ 
 "num_socio": "123456", 
 "especialidad": "Oncología", 
 "motivo": "Chequeo general" 
}


### caso 6, error técnico en RevisarAgendaHandler
POST http://localhost:8099/start
Content-Type: application/json

{ 
 "num_socio": "123456", 
 "especialidad": "Cardiología", 
 "motivo": "error-tecnico" 
}

### caso 7, sin turnos disponibles (negocio en RevisarAgendaHandler)
POST http://localhost:8099/start
Content-Type: application/json

{ 
 "num_socio": "123456", 
 "especialidad": "Cardiología", 
 "motivo": "SinTurno" 
}